export enum PROGRAM_TYPES {
  EXAMPLE_DETAIL = "EXAMPLE_DETAIL",
  EXAMPLE_FORM = "EXAMPLE_FORM",
  EXAMPLE_LIST = "EXAMPLE_LIST",
  EXAMPLE_LIST_AND_DRAWER = "EXAMPLE_LIST_AND_DRAWER",
  EXAMPLE_LIST_AND_MODAL = "EXAMPLE_LIST_AND_MODAL",
  EXAMPLE_LIST_WITH_FORM = "EXAMPLE_LIST_WITH_FORM",
  EXAMPLE_LIST_WITH_FORM_ROW = "EXAMPLE_LIST_WITH_FORM_ROW",
  EXAMPLE_LIST_WITH_FORM_LIST = "EXAMPLE_LIST_WITH_FORM_LIST",
  EXAMPLE_LIST_WITH_LIST = "EXAMPLE_LIST_WITH_LIST",
  EXAMPLE_THREE_LIST = "EXAMPLE_THREE_LIST",
  EXAMPLE_STATS = "EXAMPLE_STATS",
  EXAMPLE_CALENDAR = "EXAMPLE_CALENDAR",
  EXAMPLE_LIST_AND_MODAL_MF = "EXAMPLE_LIST_AND_MODAL_MF",

  SYS_COMMON_CODE = "SYS_COMMON_CODE",
  SYS_MENU = "SYS_MENU",
  SYS_PROGRAM = "SYS_PROGRAM",
  SYS_PROGRAM_LOG = "SYS_PROGRAM_LOG",
  SYS_USER = "SYS_USER",
  SYS_USER_GROUP = "SYS_USER_GROUP",
  SYS_USER_REQ = "SYS_USER_REQ",

  /* ##ADD_PROGRAM_TYPE_POSITION## */
}
